version: '3.4'

networks:
  profilematch: 

services:
  profilematchdb:
    container_name: profilematch-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 8002:1433
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@123
    networks:
      - profilematch

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9.7
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - profilematch

  api:
    container_name: ProfileMatch_service
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - 8001:80
    depends_on: 
      - profilematchdb
      - rabbitmq
    environment:
      - DB_HOST=profilematchdb
      - DB_NAME=ProfileMatching
    networks:
      - profilematch

